# Generated by Django 5.0.4 on 2024-04-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='datas_abertas',
            new_name='data_aberta',
        ),
    ]
